### ISSUE TITLE
Add remotes for ggb

### ISSUE THREAD

**Issue by davidruegamer** [jacobbien/trac#4]
Hi Jacob,

great package! One minor suggestion: As long as `ggb` stays on Github, maybe you could add a remotes line for `ggb` to the DESCRIPTION file, like this:

```
Remotes: jacobbien/ggb
```

This way, the installation of `trac` using `install_github` should directly search for `ggb` on Github, not on CRAN. Otherwise users of `trac` will get an error 

```
Error: Failed to install 'trac' from GitHub:
  (converted from warning) package ‘ggb’ is not available for this version of R
```

when trying to install `trac` (and some users might not know where to search for `ggb` then). Alternatively: Add one line of explanation to your README.

Awesome work!
David

**Comment by jacobbien** [comment]
Thank you, @davidruegamer for raising this issue and providing the solution!  Fixed in 8b2c5ba.
